# Generated by Django 3.2.3 on 2021-06-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='centre',
            name='address',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='centre',
            name='district',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='centre',
            name='lab_type',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='centre',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='centre',
            name='name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='centre',
            name='test_type',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
