# Generated by Django 3.2.3 on 2021-06-04 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210601_1754'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Centre',
            new_name='Center',
        ),
    ]
